---
apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping-config
data:
  CART_ENDPOINT: "cart"
  DB_HOST: "mysql"
---  
apiVersion: v1
kind: Pod
metadata:
  name: shipping
  labels:
    name: shipping
    tier: app
spec:
  containers:
  - name: shipping
    imagePullPolicy: Always
    image: vishnu7674/shipping:k8-1
    envFrom:
    - configMapRef:
       name: shipping-config
    resources:
     requests:
      cpu: "200m"
      memory: "256Mi"
     limits:
      cpu: "200m"
      memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    name: shipping
    tier: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080