---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-config
data:
  REDIS_HOST: "redis"
  MONGO_URL: "mongodb://mongodb:80/catalogue"
---  
apiVersion: v1
kind: Pod
metadata:
  name: user
  labels:
    name: user
    tier: app
spec:
  containers:
  - name: user
    imagePullPolicy: Always
    image: vishnu7674/user:v1
    envFrom:
    - configMapRef:
       name: user-config
    ports:
      - containerPort: 8080
    resources:
     requests:
      cpu: "100m"
      memory: "128Mi"
     limits:
      cpu: "100m"
      memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: user
spec:
  selector:
    name: user
    tier: app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080