apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
    tier: db
spec:
  containers:
  - name: redis
    imagePullPolicy: Always
    image: redis
    ports:
      - containerPort: 6379
    resources:
     requests:
      cpu: "100m"
      memory: "128Mi"
     limits:
      cpu: "100m"
      memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    name: redis
    tier: db
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6379
---