---
apiVersion: v1
Kind: Pod
metadata:
 name: web
 lables:
  name: web
  tier: frontend
spec:
 containers:
 - name: web
   image: vishnu7674/web:k8
   ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-service
spec:
 type: LoadBalancer
 selector:
  name: web
  tier: frontend
 ports:
  - protocol: TCP
    port: 80
    targetPort: 80